// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CamEventKind } from "./CamEventKind";
import type { CamEventLocation } from "./CamEventLocation";

export interface CamEvent { date: string, path: string, kind: CamEventKind, location: CamEventLocation, }